Zohaib/lp 503
philanthropy-u/edx-app-android pull request #11
Opened 2018-01-02 07:05 UTC by MZohaibAsaad

### Description

[LP-503](https://philanthropyu.atlassian.net/browse/LP-503)
Local Video player screen redesign with subtitles support.

### Notes
- Redesigned local video player screen
- Added download functionality for local video
- Gone with the approach of showing current video playback time in subtitle instead of title

### Design
![image](https://user-images.githubusercontent.com/32511718/34476695-dd5fa918-efb4-11e7-8a41-deddb3d1d2ff.png)

### Testing
- [ ] i18n
- [ ] RTL
- [ ] safecommit shows 0 violations
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

2018-01-16 13:59 UTC, abdulrehmanbasim requested changes

2018-01-16 13:59 UTC, abdulrehmanbasim commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/CourseUnitVideoFragment.java
> +                        if (state == null || state == DownloadEntry.DownloadedState.ONLINE) {
use else instead of this check

2018-01-16 13:59 UTC, abdulrehmanbasim commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/CourseUnitVideoFragment.java
> +    private void initializeActionabr(MenuItem menuItem) {
spelling mistake name should be `initializeActionbar `

2018-01-19 07:31 UTC, arslanashraf7 approved these changes
I have reviewed the requested changes and it seems fine to me.

2018-01-19 07:44 UTC, abdulrehmanbasim approved these changes

2018-01-19 07:45 UTC, abdulrehmanbasim approved these changes
LGTM 👍

2018-01-19 07:53 UTC, merged