Arslan/lp 447 audio
philanthropy-u/edx-app-android pull request #16
Opened 2018-01-23 07:20 UTC by arslanashraf7

### Description

[LP-447](https://philanthropyu.atlassian.net/browse/LP-447)
Enhance and implement functionality to download and play audio.

### Notes
- Created a background service to play audio in background.
- Created an Audio controller to control the playback.
- Created the Audio Player fragments to hold screens for audio.
- Extended download functionality to track and download audio files.

### Testing
- [ ] i18n
- [ ] RTL
- [ ] safecommit shows 0 violations
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

2018-01-23 11:26 UTC, MZohaibAsaad requested changes
Done with the first pass. Please make requested changes.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/drawable/icon_audio_play_pause.xml
> +        android:width="60dp"
These resources should to be moved to `dimens.xml`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/fragment_course_unit_audio.xml
> +            android:textSize="16sp"
Avoid hardcodings in resource files

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/layout_audio_player_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file should be renamed to `panel_audio_player` to match the naming convention.
Also rename `panel_player.xml` to 'panel_video_player` to keep it consistent.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/layout_audio_player_fragment.xml
> +        style="@style/video_player_panel"
Rename these resources to depict the correct use as `audio_player` views.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/notification_layout.xml
> +            android:contentDescription="a"
Use proper content description or `@null`.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/notification_layout.xml
> +            android:padding="8dp"
Avoid hardcodings in resource files.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/panel_audio_not_available.xml
> +<?xml version="1.0" encoding="utf-8"?>
This resource can be avoided and we can use `panel_video_not_available.xml` and change the error text dynamically.
Also, rename `panel_video_not_available.xml` to `panel_media_not_available.xml` after this.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/panel_player.xml
> +        <include
Use proper indentation

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/layout/panel_audio_player.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file is unused and can be removed.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/res/values/dimens.xml
> +    <dimen name="audio_thumv_bottom_shadow_size">2dp</dimen>
Please review typo mistakes.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/model/course/AudioData.java
> +        AudioData videoData = (AudioData) o;
Rename object to `audioData`.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/model/course/CourseComponent.java
> +     * return all videos blocks under this node
Update comment as per functionality

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/model/db/DownloadEntry.java
> +    public void setDownloadInfo(DownloadEntry video) {
Rename parameter to match object type

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/analytics/Analytics.java
> +    void trackMediaPlaying(String videoId, Double currentTime,
Rename parameters to match lingo as well

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/DatabaseModelFactory.java
>      private static String getVideoNetworkUrlOrNull(@Nullable VideoInfo videoInfo) {
Rename this method to `getMediaNetworkUrlOrNull`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/DatabaseModelFactory.java
> +        final String preferredVideoInfo = data.encodedAudios.getPreferredPlaybackUrl();
`e.url = preferredVideoInfo.url;`
this piece of valuable code is missing. Also rename `preferredVideoInfo` to `preferredAudioInfo`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/DbStructure.java
>      public static final int VERSION = 6;
Change to version 7

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/IDatabase.java
> +    List<DownloadEntry> getAllDeactivatedVideos(DataCallback<List<DownloadEntry>> callback);
Rename to `getAllDeactivatedMedia`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/IDatabase.java
> +    AudioModel getAudioEntryByAudioId(String audioId, DataCallback<AudioModel> callback);
This method should be removed and previous method `getDownloadEntryByMediaId` should be used.

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/DbHelper.java
> +                "ALTER TABLE " + DbStructure.Table.DOWNLOADS + " ADD COLUMN "
Same column added multiple times

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/DbHelper.java
> +                    Log.e("Zohaib", "executing");
Remove this log statement

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/DbOperationGetAudio.java
> +package org.edx.mobile.module.db.impl;
Remove this class and use `DbOperationGetDownloadEntry` instead

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/DbOperationGetVideos.java
> +class DbOperationGetVideos extends DbOperationSelect<List<DownloadEntry>> {
Suggest a more suitable generic name for this class

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/IDatabaseImpl.java
> +    public List<DownloadEntry> getAllDeactivatedVideos(final DataCallback<List<DownloadEntry>> callback) {
Rename to `getAllDeactivatedMedia`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/IDatabaseImpl.java
> +    public Integer updateMediaLastPlayedOffset(String videoId, int offset,
Rename parameters accordingly

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/IDatabaseImpl.java
> +    public AudioModel getAudioEntryByAudioId(String audioId, DataCallback<AudioModel> callback) {
Remove this method to use `getDownloadEntryByMediaId`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/db/impl/IDatabaseImpl.java
> +    public VideoModel getIDownloadEntryByMediaUrl(String mediaUrl,
This method should be removed in favour of `getDownloadEntryByMediaUrl`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/module/storage/IStorage.java
> +    void markMediaPlaying(DownloadEntry videoModel, DataCallback<Integer> watchedStateCallback);
Rename parameter accordingly

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/player/AudioController.java
> +//    private IconImageButton     mPauseButton;
Remove unused code

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/player/AudioMediaService.java
> +            if(action.equals(START_SERVICE)) {
If else if can be replaced with switch-case

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/player/AudioMediaService.java
> +                if(!isBound)
Extract this if-else to a separate method to avoid two-level nesting in a method

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/player/AudioController.java
> +public class AudioController extends FrameLayout {
Extend this class from `PlayerController`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/player/Player.java
> +    private transient AudioController audioController;
Remove this field to use only `controller`

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/CourseUnitNavigationActivity.java
> +    public static final String TEST_TAG = "TEST_TAG";
Remove this field

2018-01-23 11:26 UTC, MZohaibAsaad commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/adapters/CourseOutlineAdapter.java
> +                updateUIForVideo(viewHolder, audioData, FontAwesomeIcons.fa_volume_up);
Rename method `updateUIForVideo` to `updateUIForDownloadableMedia`

2018-01-23 15:44 UTC, arslanashraf7 commented on OpenEdXMobile/res/layout/layout_audio_player_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
actual name should have been audio_player_controller because it is the layout for controller layout not panel. And its set.

2018-01-24 06:34 UTC, MZohaibAsaad commented
Hi @arslanashraf7 ,
There is a bug in the app that audio is playing multiple times and seekbar seeks to time greater than file length as shown below:
<img src="https://user-images.githubusercontent.com/32511718/35317681-b9388536-00f9-11e8-857c-04785d33c602.png" height=450 width=250/>

### Reproduction Steps
- Play an audio
- Close app
- Play audio from notification bar
- Click on notification to open audio

Now when app opens it is showing loading screen but audio is still playing and after loading it plays audio two times synchronously. Repeat above step skipping step 3 and the audio will play 3 times at once. And seekbar will go beyond max length.

2018-01-25 07:46 UTC, MZohaibAsaad approved these changes

2018-01-25 07:46 UTC, MZohaibAsaad approved these changes
All good 👍

2018-01-26 07:04 UTC, merged